apiVersion: apps/v1
kind: Deployment
metadata:
  name: ud-ms-api-feed
  labels:
    app: ud-ms-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ud-ms-api-feed
  template:
    metadata:
      labels:
        app: ud-ms-api-feed
    spec:
      containers:
      - name: api-feed
        image: sammysium/api_feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_HOST
          - name: AWS_REGION
            value: us-east-2
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AWS_PROFILE
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AWS_BUCKET
          - name: URL
            value: localhost
          - name: JWT_SECRET
            value: secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
