apiVersion: apps/v1
kind: Deployment
metadata:
  name: ud-ms-api-feed
  labels:
    app: ud-ms-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ud-ms-api-feed
  template:
    metadata:
      labels:
        app: ud-ms-api-feed
    spec:
      containers:
      - name: api-feed
        image: sammysium/api_feed
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
