apiVersion: v1
kind: Service
metadata:
  labels:
    app: ud-ms-api-feed
  name: ud-ms-api-feed-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/ud-ms-api-feed-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ud-ms-api-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
